### ISSUE TITLE
How to do it?

### ISSUE THREAD

**Issue by ekamran** [guenard/helpscout-exporter#2]
I'm in desperate need to extract data from HelpScout,
I wish if I knew, How to use this in the first place.

Any guidance to get started?

**Comment by ekamran** [comment]
> I'm in desperate need to extract data from HelpScout,
> I wish if I knew, How to use this in the first place.
> 
> Any guidance to get started?

Everything went well except the last part where the EXPORT needs to happen in the background, it says COMMAND NOT FOUND.

**Comment by guenard** [comment]
@ekamran I don't know if you are on a Linux or macOS system but it seems that the `nohup` command does not exist for you. This command is required if you want to detach the running command from your current login/user (useful in a remote server context for example).

To run in background only, you just have to add `&` at the end of the command [as shown here](https://github.com/guenard/helpscout-exporter#3-run-the-exporter-script).

Be aware that running a command in background is optional for this script. If you can keep your Terminal / Console opened for a long time, you shouldn't worry about that.

But if you have to export lots of conversations and it takes far too long to wait, you better run this script on a remote server that will stays up and online during the export (and in that case, running with a detached user + in background will be mandatory as you won't keep the SSH connection opened for too long).

**Comment by ekamran** [comment]
@guenard Sorry for the confusion, but I'm stuck on the THIRD STEP.

It says command not found.

I'm on Mac.

**Comment by guenard** [comment]
OK so maybe something failed while running steps 1 or 2.

What do you have when you run `ls ~/.composer/vendor/bin` ?

**Comment by ekamran** [comment]
**helpscout-exporter**

_That's it._

**Comment by guenard** [comment]
@ekamran ok so if you have the command but it says "COMMAND NOT FOUND" when you run the script, it may be that you forget this part of the documentation:

> Add Composer global binaries to your path with `export PATH=$HOME/.composer/vendor/bin:$PATH` (add this line to your `~/.profile` or `~/.bashrc`).

(or just run `export PATH=$HOME/.composer/vendor/bin:$PATH` in your Terminal)

If that still does not work and you still have "COMMAND NOT FOUND", just run the command in [step 3](https://github.com/guenard/helpscout-exporter#3-run-the-exporter-script) like this:

```bash
~/.composer/vendor/bin/helpscout-exporter -o ~/helpscout-data/ > ~/helpscout-export.log &
```
